<?php

namespace MainBundle\Repository;

use MainBundle\Entity\Category;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Category $category
     *
     * @return int
     */
    public function fetchBiggestPromotion($category = null)
    {
        $qb = $this->createQueryBuilder('p');

        $today = new \DateTime();

        $qb->select('p.percent')
        ->where($qb->expr()->lte('p.startDate', ':today'))
        ->andWhere($qb->expr()->gte('p.endDate', ':today'))
        ->setParameter(':today', $today->format('Y-m-d'))
        ->orderBy('p.percent', 'DESC')
        ->setMaxResults(1);

        if($category !== null){
            $qb->andWhere($qb->expr()->eq('p.category',':category'));
            $qb->setParameter(':category', $category);
        } else {
            $qb->andWhere($qb->expr()->isNull('p.category'));
        }

        $query = $qb->getQuery();

        if($query->getOneOrNullResult() !== null){
            return $query->getSingleScalarResult();
        }
        return 0;
    }

}
